# This automatically runs pytest whenever the `backend` directory is modified, on any pushes and pulls to main or dev/backend

name: Backend Testing Pipeline

defaults:
  run:
    working-directory: backend

on:
  push:
    branches: [ "main", "dev/backend"]
    paths:
      - "backend/**"
  pull_request:
    branches: [ "main", "dev/backend"]
    paths:
      - "backend/**"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
        DB_DATABASE: ${ {secrets.DB_DATABASE }}
        DB_PORT: ${{ secrets.DB_PORT }}
      run: |
        pytest
